### ISSUE TITLE
The inconsistence between in-context examples and test cases on mathcalc

### ISSUE THREAD

**Issue by philipwangOvO** [OpenBMB/InfiniteBench#10]
Thanks for great work!
I find that [in-context examples](https://github.com/OpenBMB/InfiniteBench/blob/main/src/prompt.py) in mathcalc templates are not consistent with the [huggingface dataset preview](https://huggingface.co/datasets/xinrongzhang2022/InfiniteBench/viewer/default/math_calc)(Whether the first value is the first expected output in the answer). I am wondering whether there is a mistake in templates, which results in models' low performance on mathcalc dataset. Besides, the reason why GPT4 always output the first number as the first value may also be attributed to this inconsistency.

**Comment by chen-yingfa** [comment]
Hi!

Could you please elaborate on what template inconsistency you are referring to? For all baseline models except for GPT-4, the template should be simply the formatted string in the code. As for GPT-4, the final prompt is actually a list of messages between the AI and human, which is constructed by running the code as well.

As for the low score in Math.Calc, I do not think it is caused by a mistake because we have experimented with hand-crafted shorter inputs, and LLMs generally are not able to output all intermediate values consistently, and will inevitably go off after a few numbers. 

Finally, whether the model outputs the first value as the first predicted number does not really matter holistically, because we can simply remove it during score computation, and our preliminary results on shorter contexts does not exhibit a significant difference.

**Comment by philipwangOvO** [comment]
Thank you for your helpful response.

For example, the template in [in-context examples](https://github.com/OpenBMB/InfiniteBench/blob/main/src/prompt.py#L26) except for GPT-4 is "Let us calculate the intermediate values of an expression.\n\nExpression: 1 + 3 + 4\nValues: [1, 4, 8]\n\nExpression: 8 - 3 + 2 - 4\nValues: [8, 5, 7, 3]\n\nExpression: {context}\nValues:", which outputs the first value(1 and 8) in the expression. However, in the [huggingface dataset preview](https://huggingface.co/datasets/xinrongzhang2022/InfiniteBench/viewer/default/math_calc), the first value in the answer is 79, which is the sum of first two values(76 + 3) in the expression.

Though you have removed first value [here](https://github.com/OpenBMB/InfiniteBench/blob/main/src/compute_scores.py#L302) in GPT-4 predictions, other three models may have the same issue too due to this inconsistency, which has significant impact to their performance since values and labels are compared one by one.

Furthermore, I am wondering why the template of GPT-4 is different from others. Would GPT-4 perform better if in-context examples are added?

**Comment by chen-yingfa** [comment]
Our evaluation process takes care of that first value, if the model outputs the first value of the expression, we will simply skip it, so it has no effect on the model performance.

As for why GPT-4 requires in-context examples, it is because it has a very strong tendency to (1) reject to answer the question by saying it is out of its capabilities, and (2) output very much additional text which makes it hard to compute the scores automatically.

**Comment by philipwangOvO** [comment]
I think you have totally misunderstood my issue.

I only find the skipping first value evaluation for GPT-4 [here](https://github.com/OpenBMB/InfiniteBench/blob/main/src/compute_scores.py#L302), but **NOT** for others.

Furthermore, in your prompt, [in-context examples](https://github.com/OpenBMB/InfiniteBench/blob/main/src/prompt.py#L26) are **NOT** required by GPT-4, but required by other models. 

Based on both differences, the inconsistency between [in-context examples](https://github.com/OpenBMB/InfiniteBench/blob/main/src/prompt.py#L26) and [huggingface dataset preview](https://huggingface.co/datasets/xinrongzhang2022/InfiniteBench/viewer/default/math_calc) mentioned previously is significant for other models.

**Comment by chen-yingfa** [comment]
For "I only find the skipping first value evaluation for GPT-4 [here](https://github.com/OpenBMB/InfiniteBench/blob/main/src/compute_scores.py#L302), but NOT for others.", we have taken into account the first value for EACH MODEL MANUALLY. If it outputs the first value, we discard it, if not, we do nothing.

For "Furthermore, in your prompt, [in-context examples](https://github.com/OpenBMB/InfiniteBench/blob/main/src/prompt.py#L26) are NOT required by GPT-4, but required by other models.", it is not REQUIRED by any model per se, but it helps making the output format for manageable, which also applies to GPT-4.

Therefore, the inconsistencies have no impact on the models' performance.

**Comment by philipwangOvO** [comment]
Thank you again for your patient response and great work. I have no further questions.

**Comment by philipwangOvO** [comment]
Thank you again for your patient response and great work. I have no further questions.

**Comment by philipwangOvO** [comment]
1

**Comment by philipwangOvO** [comment]
Close Issue.

**Comment by chen-yingfa** [comment]
Thank you for your interest and patience as well, we hope that our benchmark can be useful to you.
